### ISSUE TITLE
osx-arm64 build?

### ISSUE THREAD

**Issue by ngam** [conda-forge/vowpalwabbit-feedstock#30]
This pkg is available on [via brew](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/vowpal-wabbit.rb) for arm64. Is there a plan to make it available for arm64? I suspect the current recipe won't make the cut and one would have to actually build using cmake/make... 

I can try to help if there is an interest, @xhochy 

thanks!

- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by xhochy** [comment]
If you want it, add it to the migrator list: https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/migrations/osx_arm64.txt

**Comment by ngam** [comment]
Thanks @xhochy! Done. Closing this :)
